# Site Info
title: 'TSL'
tagline: 'Today Sulim Learned'
description: '프로그래밍을 공부하며 배운점을 기록하는 공간입니다.'
baseurl: ""
url: https://sulimchoi.github.io/
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: CHOI SULIM
  description: 예비 백엔드 개발자 (CHOI SULIM)
  contact:
    # linkedin:  
    github:    https://github.com/SulimChoi
    # facebook:  
    # twitter:   
    weibo:    https://velog.io/@slchoi
    email:    mailto:slchoi7410@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:
    - '/blog/'
  Categories:
    - '/'
    # - { Categories All: '/blog/categories/' }
    - { TIL (Today I Learned): '/blog/categories/#til' }
    - { 알고리즘 문제풀이: '/blog/categories/#알고리즘-문제풀이' }
    - { etc: '/blog/categories/#etc' }
    # - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Search:
    - '/search/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'


# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'SulimChoi-github-io' # leave blank if you don't want disqus


# Use the following plug-ins
gems:
  - jekyll-paginate
